import Foundation

/**
 Stores the dictionary of words from which game boards are generated.

 This repository comes with a dictionary, `dict.txt` which is loaded into this
 actor using ``load(from:)``. The dictionary was generated by taking a list of
 100,000 most frequently used English words on the Web, and including only those
 words also found in the official Scrabble dictionary.
 */
actor Words {

    /// The words in the dictionary.
    var words = Set<String>()
    
    /**
     Loads words from a dictionary file. The file must be a normal text file,
     newline-delimited.

     - Parameter fileURL: The file to load words from.
     */
    func load(from fileURL: URL) throws {
        let fileContents = try String(contentsOf: fileURL, encoding: .utf8)
        
        // Split the file into words and add to the set
        let words = fileContents.components(separatedBy: .newlines).filter { !$0.isEmpty }
        self.words.formUnion(words)
    }
}
